### ISSUE TITLE
What variable will signal a close of trade? 

### ISSUE THREAD

**Issue by mdrobb** [7013145/pybroker#2]
Profit target percent?  Will that trigger the bot to close the trade and take profit ?

**Comment by 7013145** [comment]
Yes, that is correct. It will apply to all opened positions.

________________________________
Fra: mdrobb <notifications@github.com>
Sendt: 28. september 2017 07:18
Til: 7013145/pybroker
Cc: Subscribed
Emne: [7013145/pybroker] What variable will signal a close of trade? (#2)


Profit target percent? Will that trigger the bot to close the trade and take profit ?

**Comment by mdrobb** [comment]
great, so it will close each individual trade when it reaches that profit threshold correct ?

**Comment by 7013145** [comment]
That is correct, yes. :)


________________________________
Fra: mdrobb <notifications@github.com>
Sendt: 28. september 2017 17:59
Til: 7013145/pybroker
Cc: 7013145; Comment
Emne: Re: [7013145/pybroker] What variable will signal a close of trade? (#2)


great, so it will close each individual trade when it reaches that profit threshold correct ?

**Comment by mdrobb** [comment]
'm asking because it seems to take a while for the trades to close after they reach the positive valse specified, any reason this might be the case ?

**Comment by mdrobb** [comment]
hello i am having issues, i have my take profit set to 1% but often ive seen the trade above that and no signal for close is sent, what could be the issue?

**Comment by 7013145** [comment]
There is a limit to the calls made from any API key. This is determined using CPU time.


To make sure that your API key does not run out of CPU time, a sleep timer is fired occassionally to space out the api calls. So, the bot might do the checking and see a 0.7% profit, then sleep and miss out on a brief moment where the position is 1+% profit, and then when the bot gets to the code again it might have moved below 1% again.


You can go to the python code and find a function called "throttler()" and modify the timers in there. Just take careful note of your CPU quota available. Running out mid-trade(s) can be very crippling.


________________________________
Fra: mdrobb <notifications@github.com>
Sendt: 3. oktober 2017 18:29
Til: 7013145/pybroker
Cc: 7013145; Comment
Emne: Re: [7013145/pybroker] What variable will signal a close of trade? (#2)


hello i am having issues, i have my take profit set to 1% but often ive seen the trade above that and no signal for close is sent, what could be the issue?

**Comment by mdrobb** [comment]
I just saw it open another trade instead of first closing the active one when the trade hit the target profit percent.  It still said 1 thread was running and I have the max trade limit set to 1 so perhaps it is not closing trades properly? any thoughts ?

**Comment by mdrobb** [comment]
local variable 'pl' referenced before assignment local variable 'pl' referenced before assignment

I noticed this error could this explain it perhaps ?
