### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by mdrobb** [7013145/pybroker#3]
Any way to test new settings before putting it into production ?

**Comment by 7013145** [comment]
Unfortunately, no. However, if you have the slightest python experience it should be quite simple to re-use most of my code and add a backtest function using historical data of your choice.


I recommend depositing 0.0011 BTC and limit the bot to 1 open position at a time. That should allow you to do quite a few "test" trades on any settings of your choice, then you can always scale up if succesful. :)


________________________________
Fra: mdrobb <notifications@github.com>
Sendt: 29. september 2017 19:13
Til: 7013145/pybroker
Cc: Subscribed
Emne: [7013145/pybroker] testing (#3)


Any way to test new settings before putting it into production ?

**Comment by mdrobb** [comment]
I don't have any experience but I was able to get your program up and running with no issues, trying to tune for the USD/JPY market.
