### ISSUE TITLE
Error - "pl"

### ISSUE THREAD

**Issue by mdrobb** [7013145/pybroker#4]
Error - "local variable 'pl' referenced before assignment local variable 'pl' referenced before assignment"

seems that when it hits the take profit threshold (1%) I get this error and the thread resets and a new trade is opened but the old trade never closes, what do I need to do to fix this issue, thanks.

Linux mint 64 bit

{

"API_KEY" : "XXXXXXXXXXXXXXXXXXXXXXX" ,

"SYMBOL" : "USDJPY" ,

"UNIT" : 0.001 ,

"LEVERAGE_MULTIPLIER" : 0.05 ,

"CANDLE_RESOLUTION" : 60 ,

"STOP_LOSS_MULTIPLIER" : 150 ,

"TARGET_PIN_SIZE" : 66 ,

"TRADES_LIMIT" : 1 ,

"PROFIT_TARGET" : 1 ,

"PROFIT_TARGET_PERCENT" : 50 ,

"TAKE_PROFIT" : 1,

"TAKE_PROFIT_PERCENT" : 1,

"TOTAL_TRADES_CAP" : 5

}

Here is a copy of my config file if that helps?

**Comment by 7013145** [comment]
I am not quite sure, unfortunately. I will try to take a look at the code sometime in the near future, and update the github code. Can't give you any timeframe unfortunately.


I encourage you to take up python programming! It is very simple to understand and incredibly powerful once you get a hang of it.


________________________________
Fra: mdrobb <notifications@github.com>
Sendt: 5. oktober 2017 23:32
Til: 7013145/pybroker
Cc: Subscribed
Emne: [7013145/pybroker] Error - "pl" (#4)


Error - "local variable 'pl' referenced before assignment local variable 'pl' referenced before assignment"

seems that when it hits the take profit threshold (1%) I get this error and the thread resets but the trade never closes, what do I need to do to fix this issue, thanks.

{

"API_KEY" : "XXXXXXXXXXXXXXXXXXXXXXX" ,

"SYMBOL" : "USDJPY" ,

"UNIT" : 0.001 ,

"LEVERAGE_MULTIPLIER" : 0.05 ,

"CANDLE_RESOLUTION" : 60 ,

"STOP_LOSS_MULTIPLIER" : 150 ,

"TARGET_PIN_SIZE" : 66 ,

"TRADES_LIMIT" : 1 ,

"PROFIT_TARGET" : 1 ,

"PROFIT_TARGET_PERCENT" : 50 ,

"TAKE_PROFIT" : 1,

"TAKE_PROFIT_PERCENT" : 1,

"TOTAL_TRADES_CAP" : 5

}

Here is a copy of my config file if that helps

**Comment by mdrobb** [comment]
Oh sorry to hear it's a bigger issue then expected.  I have started looking into it more I hope to learn a lot from this project and the next.  If you have any pointers as to where the code might be going  wrong please share.

Thanks

**Comment by 7013145** [comment]
My apologies, I took a quick look at what might be wrong out of curiosity and it was simply an embarrasing typo by me. It is fixed now, so you can overwrite your pybroker folder by downloading it again from this repository and it will close on % profit too. :) again, thanks for pointing this error out to me.

**Comment by mdrobb** [comment]
progress has been made I downloaded and ran the new code and now I get a signal that the trade is above threshold and closing... but the trade still remains open though no second trade is placed as before.

**Comment by 7013145** [comment]
Now it should work, accidentally removed the `position_close(id)` calls on previous fix ;)

**Comment by mdrobb** [comment]
great ! ill give it another go !
